USE PROJETO

INSERT INTO FORNECEDOR ( ID_FORN, NOME, TELEFONE)
VALUES (01, 'chronic', 103931);

INSERT INTO PEDIDO ( COD_PEDIDO, DT_ENTREGA, DT_PEDIDO)
VALUES (01, '2024-11-18', '2024-11-17');

INSERT INTO TIPO_PRODUTO ( CODIGO_TIPO, DESCRIÇÃO)
VALUES (01, 'Camiseta Chronic 3983')

INSERT INTO endereco ( ID_END, CEP, CIDADE, RUA, BAIRRO, NÚMERO, ESTADO, ID_FORN)
VALUES (01, 03016-010, 'SÃO PAULO', 'RUA MARIA JOAQUINA', 'BRÁS', 340, 'SP', 01);

INSERT INTO CLIENTE ( ID_CLIENTE, TELEFONE, NOME, ID_END)
VALUES (01, 1198756352, 'GUSTHAVO', 01);

INSERT INTO produto ( ID_PROD, PREÇO, DESCRICAO, NOME, QUANTIDADE, CODIGO_TIPO)
VALUES (01, 90, 'CAMISETA AZUL ESTAMPA CHRONIC', 'CAMISETA', 01, 01);

INSERT INTO REALIZA ( ID_CLIENTE, COD_PEDIDO)
VALUES (01, 01);

INSERT INTO FORNECE ( ID_FORN, ID_PROD)
VALUES (01, 01);

INSERT INTO CONTEM ( COD_PEDIDO, ID_PROD)
VALUES (01, 01);