CREATE DATABASE Projeto;

CREATE TABLE PEDIDO  (
COD_PEDIDO INT(5) PRIMARY KEY,
DT_ENTREGA DATE,
DT_PEDIDO DATE
);

CREATE TABLE CLIENTE (
ID_CLIENTE INT(7) PRIMARY KEY,
TELEFONE INT(13),
NOME VARCHAR(60),
ID_END INT(7),
FOREIGN KEY(ID_END) REFERENCES ENDERECO (ID_END)
);

CREATE TABLE FORNECEDOR (
ID_FORN VARCHAR(7) PRIMARY KEY,
NOME VARCHAR(40),
TELEFONE INT(13)
);

CREATE TABLE PRODUTO (
ID_PROD INT(7) PRIMARY KEY,
PREÇO INT(9.2),
DESCRICAO VARCHAR(200),
NOME VARCHAR(50),
QUANTIDADE INT(10),
CODIGO_TIPO INT(7),
FOREIGN KEY(CODIGO_TIPO) REFERENCES TIPO_PRODUTO (CODIGO_TIPO)
);

CREATE TABLE TIPO_PRODUTO (
CODIGO_TIPO INT(7) PRIMARY KEY,
DESCRIÇÃO VARCHAR(200)
);

CREATE TABLE ENDERECO (
ID_END INT(7) PRIMARY KEY,
CEP INT(10),
CIDADE VARCHAR(30),
RUA VARCHAR(70),
BAIRRO VARCHAR(40),
NÚMERO INT(7),
ESTADO VARCHAR(30),
ID_FORN VARCHAR(7),
FOREIGN KEY(ID_FORN) REFERENCES FORNECEDOR (ID_FORN)
);

CREATE TABLE REALIZA(
ID_CLIENTE INT(7),
COD_PEDIDO INT(5),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
FOREIGN KEY(COD_PEDIDO) REFERENCES PEDIDO (COD_PEDIDO)
);

CREATE TABLE FORNECE(
ID_FORN VARCHAR(7),
ID_PROD INT(7),
FOREIGN KEY(ID_FORN) REFERENCES FORNECEDOR (ID_FORN),
FOREIGN KEY(ID_PROD) REFERENCES PRODUTO (ID_PROD)
);

CREATE TABLE CONTEM (
COD_PEDIDO INT(5),
ID_PROD INT(7),
FOREIGN KEY(COD_PEDIDO) REFERENCES PEDIDO (COD_PEDIDO),
FOREIGN KEY(ID_PROD) REFERENCES PRODUTO (ID_PROD)
);

